// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID          int64
	Lastloginat pgtype.Timestamp
	Createdat   pgtype.Timestamp
	Updatedat   pgtype.Timestamp
}

type Category struct {
	ID        int64
	Title     pgtype.Text
	Createdat pgtype.Timestamp
	Updatedat pgtype.Timestamp
}

type Post struct {
	ID         int64
	Title      pgtype.Text
	Content    pgtype.Text
	Createdat  pgtype.Timestamp
	Updatedat  pgtype.Timestamp
	Authorid   pgtype.Int8
	Categoryid pgtype.Int8
}

type Token struct {
	ID        int64
	Token     string
	Expiredat pgtype.Timestamp
	Tokentype string
	Createdat pgtype.Timestamp
	Updatedat pgtype.Timestamp
}

type User struct {
	ID        int64
	Name      string
	Password  string
	Email     string
	Createdat pgtype.Timestamp
	Updatedat pgtype.Timestamp
}
