// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID       int64
	Email    string
	Fullname pgtype.Text
	Password string
}
