// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"
	"time"
)

type Account struct {
	ID          int64
	Lastloginat sql.NullTime
	Createdat   sql.NullTime
	Updatedat   sql.NullTime
}

type Category struct {
	ID        int64
	Title     sql.NullString
	Createdat sql.NullTime
	Updatedat sql.NullTime
}

type Post struct {
	ID         int64
	Title      sql.NullString
	Content    sql.NullString
	Createdat  sql.NullTime
	Updatedat  sql.NullTime
	Authorid   sql.NullInt64
	Categoryid sql.NullInt64
}

type Token struct {
	ID        int64
	Token     string
	Expiredat time.Time
	Tokentype string
	Createdat sql.NullTime
	Updatedat sql.NullTime
}

type User struct {
	ID        int64
	Name      string
	Password  string
	Email     string
	Createdat sql.NullTime
	Updatedat sql.NullTime
}
